version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "12345"
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysql
    networks:
      wordpress_network:
        ipv4_address: "10.70.70.2"

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "12345"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      wordpress_network:
        ipv4_address: "10.70.70.3"

networks:
  wordpress_network:
    ipam:
      driver: default
      config:
        - subnet: "10.70.70.0/24"

