version: "2.21.0"
services:
  website1:
    image: nginx
    ports:
      - "8081:80"
    restart: always
  website2:
    image: nginx
    ports:
      - "8082:80"
    restart: always
    networks:
      hamza:
        ipv4_address: 192.168.16.253

networks:
  hamza:
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24